### ISSUE TITLE
Make list of popular frameworks 

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#1]
This is the list we could come up with for now. Please add if there are more. We create an issue (with a link) if we think the framework is important enough to further investigate the convertors available.
Must have:
- Pytorch #2 
- Tensorflow #3 
- Keras #4 
- MXNet #5 
- Caffe2 #6 
- SKLearn #11 

Should have:
- DL4J
- Theano
- H2O.ai
- Chainer
- Fastai
- XGBoost
- LightGBM

Could have:
- Darknet #7 
- Caret
- Catboost
- Prophet
- Tidymodels
- Microsoft CNTK

Won't have:
- Jax, because I hardly see it mentioned.

**Comment by cwmeijer** [comment]
This image is from 2018 and shows some usage statistics:
![image](https://user-images.githubusercontent.com/6087314/109940700-a8172e80-7cd2-11eb-8ca5-8b1b6a1e09e3.png)
source https://www.kdnuggets.com/2018/09/deep-learning-framework-power-scores-2018.html

Here's one skills asked for in job openings from 2019:
![image](https://user-images.githubusercontent.com/6087314/109941310-4efbca80-7cd3-11eb-9f69-592187dd37e9.png)
Source with some similar statistics https://minddata.org/popular-deep-learning-frameworks-in-2019-tensorflow-pytorch-Brian-Ka-Chan-AI

Kaggle survey from 2020:
![image](https://user-images.githubusercontent.com/6087314/109944202-45279680-7cd6-11eb-9b4e-41c9b874b3c6.png)
Source https://www.kaggle.com/kaggle-survey-2020.

**Comment by cwmeijer** [comment]
Because the list was getting quite long, I made some prioritization based on the statistics I posted above, and my own feeling about the purpose of these frameworks. There were quite a few frameworks that I never heard of, so feel free to comment on the list and prioritization.

**Comment by loostrum** [comment]
Must have list looks good to me.

Should have: 
Microsoft CNTK is [deprecated](https://docs.microsoft.com/en-us/cognitive-toolkit/news), so we can probably skip it

I have no further experience with any of the others, so I trust the list you made :)

**Comment by cwmeijer** [comment]
I'm closing this because there is no more work required for this list. We'll still use the issue for reference.
