### ISSUE TITLE
Create a repo using the cookie cutter tool

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#101]

**Comment by loostrum** [comment]
The repo is now live at https://github.com/dianna-ai/dianna/
Some issue were generated automatically, for further finalizing the repo. See https://github.com/dianna-ai/dianna/issues
I'll see which ones of those we could already do.

**Comment by loostrum** [comment]
All integrations (zenodo etc) are now set up as far as possible. Remaining tasks can only be finished after the first release so closing this issue.
