### ISSUE TITLE
Make some schematic of the architecture of our tool present to the team

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#103]
This issue is not blocked by, but dependent on exploring implemntations (#78 #76 #79 #80 #81) and on the functionality that we want (user stories #102).

Any ideas about architectural choices that we could make can be added here as comments.

**Comment by elboyran** [comment]
Top level architecture drawing creating using [draw.io](https://app.diagrams.net/) saved as drawio and PNG at [Share Point Architecture](https://nlesc.sharepoint.com/sites/DIANNA/Shared%20Documents/General/Architecture) and [Teams Files](https://teams.microsoft.com/_#/files/General?threadId=19%3A1c10950e7e484a80881256db07819b07%40thread.tacv2&ctx=channel&context=Architecture&rootfolder=%252Fsites%252FDIANNA%252FShared%2520Documents%252FGeneral%252FArchitecture).

**Comment by elboyran** [comment]
Some of the design choices of the [iNNvestigate library](https://github.com/albermax/innvestigate) are explained and illustrated in this [notebook for developers](https://github.com/albermax/innvestigate/blob/master/examples/notebooks/introduction_development.ipynb).

**Comment by elboyran** [comment]
After the discussion session we decided to go for some prototyping. @loostrum and @geek-yang will do some pair programming using the Captum knowledge/experience, @cwmeijer will look into RISE. @elboyran will look at user stories and possibly PatternAttribution (or the choices made by iNNvestigate) if there is time.

**Comment by loostrum** [comment]
Creating a prototype in the other repo: https://github.com/dianna-ai/dianna/tree/prototype
The tutorials folder contains a script to run the code.
