### ISSUE TITLE
Add text-based user story

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna-exploration#117]
Look in SSI or other projects (NLP SIG) for examples. Related to #102 and #116.

**Comment by elboyran** [comment]
Talked to Erik about NEWSGAG project. He pointed me out to the [project's publication](https://arxiv.org/abs/1810.00968). I will try to define some user stories from the paper's motivation and then he will check them out in the document of issue #116 .

**Comment by cwmeijer** [comment]
Great stories! They're very useful!
