### ISSUE TITLE
Update design schematic

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna-exploration#120]
- [x] Add new methods (LIME and/or LRP)
- [ ] Reflect in general

https://app.diagrams.net/#Wb!UPZtKeipi0WrFvKBlrEPP4gCzfYL1_ZNqqeyKlYhp43xuB7DeGf3QZ8Mqz5yc_MZ%2F01YA33DUP4W7ISPOFPEBBJTNI4MHVRSL4E

**Comment by loostrum** [comment]
Added LIME and the text visualization

**Comment by cwmeijer** [comment]
Patrick and I added/updated. I think @loostrum will updates as well (for instance for the helper functions he wrote). After that, this issue can be closed.

**Comment by loostrum** [comment]
i added the helper function and double-checked that we're not missing any packages in the schematic.
