### ISSUE TITLE
Expand LIME to work with images

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna-exploration#122]

**Comment by elboyran** [comment]
Related user stories:

> As a domain user I want to see a heatmap for evidence towards classifying something to class A to understand my model’s decision making. 
> 
>  
> 
> As a domain user I want to see a heatmap for evidence against classifying something to class A to understand my model’s decision making.

**Comment by elboyran** [comment]
Chris suggested to fork from branch 111 (from the dianna repo, not from dianna-exploration!), as the API has changed.

**Comment by elboyran** [comment]
Updating my Virtual Box everything crashed and couldn't fir it today. :-( Next week, have again urgent deadline, can someone else pick this up? Patrick?

**Comment by loostrum** [comment]
LIME on images is now working. Still want to investigate the enormous virtual memory usage when using the DIANNA implementation, which is not present when using the original implementation

**Comment by loostrum** [comment]
Memory usage problem is fixed (there were missing arguments in the call to lime). 
https://github.com/dianna-ai/dianna/pull/18 implements LIME for images
