### ISSUE TITLE
Create heatmap visualization for text

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#124]
What format should the output have? html or image?

**Comment by cwmeijer** [comment]
Conclusion from standup: use html and see if we can find an html to image convertor to add as a dependency.

**Comment by loostrum** [comment]
LIME's visualization for HTML + text seems to be mostly located in two methods:
[Explanation.as_html()](https://github.com/marcotcr/lime/blob/fd7eb2e6f760619c29fca0187c07b82157601b32/lime/explanation.py#L222) Generates a HTML page, while [TextDomainMapper.visualize_instance_html()](https://github.com/marcotcr/lime/blob/fd7eb2e6f760619c29fca0187c07b82157601b32/lime/lime_text.py#L51) seems to create a string representing a highlighted word.
These two methods are quite tightly integrated into the LIME architecture, so if we want to use it for all our text visualization it might be easier to implement our own version based on LIME's code.

**Comment by cwmeijer** [comment]
We could use imgkit to convert html+css to an image.

**Comment by loostrum** [comment]
basic html+css highlighting is now implemented.

**Comment by cwmeijer** [comment]
I think we should skip saving html as image. I couldn't find a dependency that easily installs through pip that could take care of converting html to an image file. I found some packages, like imgkit, that could do it, but that requires you to install extra stuff through apt (linux) or by downloading binaries manually (windows). The benefits of having a clean installation procedure outweighs the convenience of outputting text heatmaps as images. We could make installation of such html packages optional but let's discuss that first before we decide.

**Comment by cwmeijer** [comment]
Also, I tried to implement showing our text visualization (html) in a notebook. I did not figure out how to do that exactly yet. I'll have another look next week.

**Comment by egpbos** [comment]
I would recommend ipywidgets. They can also show raw HTML: https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#HTML

**Comment by elboyran** [comment]
Related user story:

> As a domain user I want to see a heatmap for the contributions of each word in an article towards and against classifying it to a specific genre to trust and understand an ML model’s decision making.
