### ISSUE TITLE
Test/play with *original* implementation of LRP

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#128]
results from captum implementation (#78) were a bit disappointing and not as good as the paper's examples.

See if we can replicate the papers results with the original implementation.

**Comment by cwmeijer** [comment]
2 options to continue:
- look into original implementation
- look into algorithm

In the meantime ask LRP author for comment on results.

**Comment by cwmeijer** [comment]
We looked at the iNNvestigate package. This seems to be a maintained and recent version of LRP. The packages seems to have quite some users even and more importantly, the original author of the LRP paper is one of the main authors/contributor of iNNvestigate. 
However, we couldn't get the package to run. It is complaining about Keras attributes that are not there. We tried it on 2 machines. Also, there own build has been failing for the last 2 years.

Having iNNvestigate as a dependency for DIANNA does not seem to be an option because of this. We would probably need to implement this algorithm ourselves if we want it available in DIANNA. Given that the algorithm needs access to information from layers within the neural net in ONNX format, this will be quite task (or a mini project).

We think it is too cumbersome and time consuming to continue trying for now. We propose to close the issue.

**Comment by elboyran** [comment]
I should have warned you more clearly about it (that is repeat my experience again)- I also couldn't make it run for a while in the past, until I found the problem with the Keras version- layers should be named! I hope you didn't lose too much time.

**Comment by elboyran** [comment]
Please, note that the iNNvestiagation implementation (by the original authors) also does give scores only within the MNIST digits!
Please, see this [notebook example](https://github.com/albermax/innvestigate/blob/master/examples/notebooks/mnist_compare_methods.ipynb).
