### ISSUE TITLE
Binary MNIST dataset

### ISSUE THREAD

**Issue by fdiblen** [dianna-ai/dianna-exploration#149]
It would be nice if the Binary MNIST dataset is available for users to download instead of generating it. Would you consider uploading the dataset to Zenodo and refer to it in https://github.com/dianna-ai/dianna#datasets?

**Comment by egpbos** [comment]
Please use the https://github.com/dianna-ai/dianna main repo for filing issues :)

We should probably disable issues here to avoid confusion.

**Comment by fdiblen** [comment]
created an issue here: https://github.com/dianna-ai/dianna/issues/313
closing this one.
