### ISSUE TITLE
Ontologize DIANNA XAI methods in current XAI landscape

### ISSUE THREAD

**Issue by WillemSpek** [dianna-ai/dianna-exploration#156]
Goal is to create a concrete ontology of the current approaches to XAI and find out where our methods lie. This should provide a clearer view on the abstract nature of these algorithms and what tradeoffs there are between them.

**Comment by egpbos** [comment]
Sounds interesting! Are you aware of the survey that was done of existing methods at the beginning of the DIANNA project? I guess you will build on that in some way? Or is the intent to go more in depth on the actual algorithms based on original source material? Or something entirely different? :)

**Comment by WillemSpek** [comment]
Yes, I am well aware! This was serving as a means for me to get acquainted with the field. Additionally, I will be investigating beyond XAI; how it can be understood, quantitatively evaluated and made intuitive for end-users!
