### ISSUE TITLE
Extract XAI methods from paper Arrietta et al. - XAI: concepts, taxonomies ...

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#18]
Issue is sub issue from #8 
Create an initial list of XAI methods to chose from. Extract from this paper

**Input**
Possible starting points to get references from: 

-  Arrietta et all. ["Explainable Artificial Intelligence (XAI): Concepts, taxonomies, opportunities and challenges toward responsible AI"](https://doi.org/10.1016/j.inffus.2019.12.012), Information Fusion 58 (2020) pp. 82–115, aka "taxonomy paper"

**Output**
Add a [document](https://nlesc-my.sharepoint.com/:w:/g/personal/e_ranguelova_esciencecenter_nl/EctKDvZSDGlJqEfVaW6d-sgB3S8Yyou3oYcJMsF0wdrQlw?e=UYhR4X) to help to decide on the initial list.

**Comment by elboyran** [comment]
Issue #8 has been closed- initial list of XAI methods has been made.
