### ISSUE TITLE
Investigate convertors for Pytorch

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#2]
refs #1 
Do these convertors exist? 
- [x] Pytorch -> ONNX

Add links to the convertors in comments below. Also, comment if they were tested and if they work well and such.

**Comment by elboyran** [comment]
I think that we need only 1 directional conversion. Only to have the input model of interest in ONNX. In order to create a heatmap as output.

**Comment by loostrum** [comment]
@elboyran alright, then we'll focus on the Pytorch -> ONNX conversion only (and the same for the other frameworks).

**Comment by loostrum** [comment]
Pytorch to ONNX converter is included in Pytorch.
Tutorial: https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html
Code: https://github.com/pytorch/pytorch/tree/master/torch/onnx
Docs: https://pytorch.org/docs/master/onnx.html

**Comment by loostrum** [comment]
Pytorch converter works, i.e. the model output is the same from within pytorch as with the ONNX model and runtime.
Exporting to ONNX  requires a forward pass through the network, so some random input data as well. This fixes the input shape the ONNX model accepts, unless an axis is set to "dynamic" when exporting.

**Comment by loostrum** [comment]
Reopened for adding a code example
