### ISSUE TITLE
Clean the current XAI methods list

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#20]
Edit the list in #8. Make a final selection of methods from that list.

**Comment by elboyran** [comment]
I have gone through the list and marked all methods with Y[es] and N[o] in the Final column. I have also added 1 (actually with 2 flavors) more method. If there are no objections, I can delete the rows marked with N or simply we use only rows marked by Y in the models evaluation table.

**Comment by elboyran** [comment]
I want to bring a scope issue for discussion. All methods in our list so far look at **individual predictions**.
There are some methods helping with **semi-automatic analysis of "heatmaps" over large datasets**. It seems like a very useful tool for a scientist, but is a different scope. _Would we like to also have such a tooling in DIANNA?_

Example is SpRAy (spectral relevance analysis).
Paper: https://www.researchgate.net/publication/331397043_Unmasking_Clever_Hans_Predictors_and_Assessing_What_Machines_Really_Learn

Most informative is Figure 3.

Quote from the paper: 
> Explanation techniques enable inspection of the decision process on a single instance basis. However, screening through a large number of individual explanations can be time consuming. To efficiently investigate classifier behavior on large datasets, we propose a technique: spectral relevance analysis (SpRAy). SpRAy applies spectral clustering53on a dataset of LRP explanations in order to identify typical, as well as atypical decision behaviors of the machine-learning model, and presents them to the user in a concise and interpretable manner.

> Technically, SpRAy allows one to detect prediction strategies as identifiable on frequently reoccurring patterns in the heatmaps, e.g., specific image features. The identified features may be truly meaningful representatives of the object class of interest, or they may be co-occurring features learned by the model but not intended to be part of the class, and ultimately of the model’s decision process.

Some code: 

> Source code for LRP and sensitivity analysis is available athttps://github.com/sebastian-lapuschkin/lrp_toolbox.

(This is the OLD version, the new is in iNNvestigate. I've had a correspondence with the programmer in the past)

> Source code for SpectralClustering and t-SNE as used in the SpRAy method is available from the scikit-learn athttps://github.com/scikit-learn/scikit-learn.

**The team is up for it if we have time!**

**Comment by elboyran** [comment]
I also want to point your attention to section **VII B. From Explanations to Novel Scientific Insights.** from the last paper listed in Issue #8: ["Explaining Deep Neural Networks and Beyond: A Review of Methods and Applications"](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9369420).

I recommend that we all read it for examples of what XAI has been used in the sciences, though have in mind, the authors of this review paper are **ALSO** the authors of LRP and SpRAy, so they are kind of biased ;-)

**Comment by elboyran** [comment]
Did some sort of a rough sorting of the methods.
