### ISSUE TITLE
Create new issue for every single XAI method

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#21]
For every method in the final list of XAI methods (see #20), create a separate github issue to evaluate the method by the evaluation criteria.

----------------

Common text:

Evaluate the ___ method based on the evaluation criteria from issue #9 and fill in the results in the table created in issue #23.
- Paper: link
- Blog: link
- Presentation: link
- Implementation(s): links

-------------

- [x] DTD, #24 
- [x] LRP, #25 
- [x] IG, #26 
- [x] LIME, #27 
- [x] SHAP, #28 
----
- [x] PN, #29 
- [x] PA, #29 
- [x] DeepLIFT, #30 
- [x] SmoothGrad, #31 
- [x] CLEAR, #32 
- [x] Deconvnet, #33 
- [x] Grad-CAM, #34 
- [x] RISE, #34

**Comment by elboyran** [comment]
- [ ] DTD
- [ ] LRP
- [ ] IG
- [ ] LIME
- [ ] SHAP
----
- [ ] PN
- [ ] PA
- [ ] DeepLIFT
- [ ] SmoothGrad
- [ ] CLEAR
- [ ] Deconvnet
- [ ] Grad-CAM
- [ ] RISE
