### ISSUE TITLE
Setup table with methods versus criteria

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#23]
Create some table, possibly in word 365, but alternatively in MD or other format, that contains all the evaluation criteria from #9 versus the seelcted XAI methods from #20. The table should be easily editable by all team members.

**Comment by elboyran** [comment]
Aim for evaluation of each criteria with one word, e.g. : 

- _present/non-present_, e.g. for V1 User studies and V2 for Synthetic Experiments or U7 Coherence, etc.

- _good/not good_ (in respect to our goals), e.g. for S3 Explanation Invariance, etc.

-  _categorical_, e.g. _post-hoc_ for F7 Relation to the Predictive System, _model-agnostic_ for F6 Applicable Model Class, _local/global_ for F4 Explanation Breadth/Scope etc.

**Comment by elboyran** [comment]
The table and some short reminders of the criteria definitions and way of evaluating are given in this [document](https://nlesc-my.sharepoint.com/:w:/g/personal/e_ranguelova_esciencecenter_nl/EQ9JceCi70hFlUggTIqboIABWzr-kcFrin6GgOxO_JFg0g?e=sfuWeE).
