### ISSUE TITLE
Evaluate LRP

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna-exploration#25]
Evaluate the Layer-wise Relevance Propagation (LRP) method based on the evaluation criteria from issue #9 and fill in the results in the [table](https://nlesc-my.sharepoint.com/:w:/g/personal/e_ranguelova_esciencecenter_nl/EQ9JceCi70hFlUggTIqboIABWzr-kcFrin6GgOxO_JFg0g?rtime=vzQ-gdr42Eg) created in issue #23.

 - [Paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0130140)
 - [Blog](http://danshiebler.com/2017-04-16-deep-taylor-lrp/)
-  Implementation(s): lin [iNNvestigate](https://github.com/albermax/innvestigate)

**Comment by cwmeijer** [comment]
Not sure yet, but I think Deep Taylor decomposition #24, which is already assigned to me, is almost the same as LRP. It is probably convenient and efficient if I evaluate them both.
