### ISSUE TITLE
Evaluate SHAP

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna-exploration#28]
Evaluate the SHAP method based on the evaluation criteria from issue #9 and fill in the results in the table created in issue #23.

- [Paper](https://arxiv.org/abs/1705.07874)

- [Blog](https://towardsdatascience.com/shap-how-to-interpret-machine-learning-models-with-python-2323f5af4be9)

- Implementation(s): [shap](https://github.com/slundberg/shap), [InterpetML](https://github.com/interpretml/interpret), [Tensorboard What-If tool](https://www.tensorflow.org/tensorboard/what_if_tool)

**Comment by geek-yang** [comment]
The author of SHAP paper suggests adapting DeepLIFT to approximate the SHAP values for deep neural networks. Therefore, I will review the DeepLIFT method as well.
