### ISSUE TITLE
Investigate convertors for Tensorflow

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#3]
refs #1 
Do these converters exist? 
- [x] Tensorflow-> ONNX

Add links to the convertors in the comments below. Also, comment if they were tested and if they work well and such.

**Comment by loostrum** [comment]
The [tensorflow-onnx](https://github.com/onnx/tensorflow-onnx) package supports conversion from TF1.x, TF2.x, and tf.keras.
Installation and usage is easy, but requires python < 3.9 (as does tensorflow itself)

**Comment by loostrum** [comment]
Reopened for adding a code example
