### ISSUE TITLE
Evaluate DeepLIFT

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna-exploration#30]
Evaluate the DeepLIFT method based on the evaluation criteria from issue #9 and fill in the results in the table created in issue #23.

- [Paper](https://arxiv.org/pdf/1704.02685.pdf)
- [Video tutorial - 6 parts](http://goo.gl/qKb7pL)
- [ICML talk](https://vimeo.com/238275076)
- [Author’s code](https://vimeo.com/238275076)- python library supporting only Keras models. Note [some of the FAQ ](https://github.com/kundajelab/deeplift#my-model-architecture-is-not-supported-by-this-deeplift-implementation-what-should-i-do) for supported architectures about relationship with DeepSHAP and DeepExplain! iNNvestigate opted for a wrapper around the code. Captum and others also have implemented it. Also in [DeepExplain](https://github.com/marcoancona/DeepExplain).

**Comment by geek-yang** [comment]
In the DeepLIFT paper, the authors claim that DeepLIFT is better than Integrated Gradient, LRP and Grad-CAM. These methods are very similar and only differ in the quantification of gradients, and the compliance of some rules on their own definition (e.g. definition of contributions, treatment of some special cases, etc.). A complete evaluation of this method should include a comparison with IG, LRP and Grad-CAM.
