### ISSUE TITLE
Evaluate SmoothGrad

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna-exploration#31]
Evaluate the SmoothGrad method based on the evaluation criteria from issue #9 and fill in the results in the table created in issue #23

- [Paper](https://arxiv.org/abs/1706.03825)
- [Demo] (https://pair-code.github.io/saliency/) 
- [code](https://github.com/pair-code/saliency)

**Comment by loostrum** [comment]
Smoothgrad seems to be mostly meant as an addition on top of existing gradient methods
