### ISSUE TITLE
Find an accessible location for only the team, to store our datasets

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna-exploration#42]
The shared folder was created here:
https://surfdrive.surf.nl/files/index.php/apps/files/?dir=/Projects/Dianna

**Comment by cwmeijer** [comment]
I created a shared folder on surfdrive. I believe it should be good for ~450 GB. 
https://surfdrive.surf.nl/files/index.php/apps/files/?dir=/Projects/Dianna
I shared it with all of our team members, from both escience center and surfsara.

**Comment by egpbos** [comment]
👍 Just FYI: if you have SURFdrive setup to sync to your laptop, there's an option that makes it ask for permission when it tries to sync large folders, may be good to activate at this point.

**Comment by loostrum** [comment]
I can't add files to the shared folder, surfdrive complains with `Not allowed because you don't have permission to add subfolders to that folder`
