### ISSUE TITLE
Simple geometric dataset

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna-exploration#43]
Discover or create simple 2 class geometric shapes dateset in order to demo how to study the properties of the XAI heatmaps.

Add scripts at [dataset_script folder](https://github.com/dianna-ai/dianna/tree/main/datasets_scripts)

**Comment by elboyran** [comment]
The _babyAI dataset_ of simple shapes (ellipses, squares and triangles) mentioned in this [blog](https://medium.com/neural-networks-performance/neural-networks-performance-on-babyai-dataset-part-i-6991ab065ebe), unfortunately does not exist any more.

**Comment by elboyran** [comment]
A bit of the motivation for creating such a dataset is available at my [IEEE 2018 Extended Abstract](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8588726).

**Comment by elboyran** [comment]
The creation and experiments with the Triangles and Squares dataset I've been playing with is documented in my [XAI repo](https://github.com/NLeSC/XAI).
A good starting point is the [Demo notebook](https://github.com/NLeSC/XAI/blob/master/Software/TrianglesAndSquaresRotationAndScaleDemo/eXplAInabilityTrianglesAndSquaresRotScaleDemo.ipynb) pointing to other notebooks, including the data generation. The original MATLAB software (by a co-author of the IEEE publication) can be found at the same repo: [Simple LRP Experiment/data_generation](https://github.com/NLeSC/XAI/tree/master/Software/MATLAB/SimpleLRPExperiment/data_generation)

**Comment by elboyran** [comment]
I think we need a brainstorming session for deciding on the creation.

**Comment by elboyran** [comment]
**Goals:**
 
- supply users with a dataset  suitable for easy analysis (similar to sensitivity analysis) of the XAI heatmap properties.  
- use it in our demo/tutorial/documentation along with  simple trained ONNX model.
- (Long-term ambition: replace MNIST as a benchmark for XAI researches)


**Design restrictions:**

Restriction &#8592; _motivation_

* Have only 2-class classification problem. &#8592; _Easiness to facilitate "Why A, but not B?" explanations. See for example Fig 12 on page 27/46 from the [LRP paper ](https://storage.googleapis.com/plos-corpus-prod/10.1371/journal.pone.0130140/1/pone.0130140.pdf?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=wombat-sa%40plos-prod.iam.gserviceaccount.com%2F20210421%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20210421T112742Z&X-Goog-Expires=3600&X-Goog-SignedHeaders=host&X-Goog-Signature=0027d6befb073adebe4299f442f1ecd0201251a8729169d262de866163f5590b0bd27f50e61394cd2b28c3f2ee79d834b15b79c2b1c9ed6ac2f245644f376329e22dcbfb87054a11cfda6a9668fef10bcbd6614a070e1490ab95d964b33bbf45b146ddb602d437cb2f4ca629efc09b3a3bcafdd30235dd693d14983e515dd313ce00e6c02d682f24ee8d20cecb975b498de186d9f395eb609f574e8c121964110d81b523e1a01f9e890baf42dfc07e87561a89cddd610fb313a917f007f2ed3a5c5fcd07c3b8114c0cb27d91fb7afadfc71f15cba6a77171445e06d62d02baa4fbac671dbf369975e2369d2e541fdc27b429cfeee33797744e2ef1e0c06db79c) for the difficulty with MNSIT_
* Have simple geometric shapes which can be "morphed" from one to the other, e.g. squares and circles &#8592; _Exploring when dies the model "flip" the prediction between the classes, see slide 15 from the [Kick-off presentation](https://nlesc-my.sharepoint.com/:p:/g/personal/e_ranguelova_esciencecenter_nl/EQGNhUfou_JKklpvDNpWkIYBMkmsp-DQktd-VwIFUEScgw?e=Ep9qjk)_. 
  * Use "pure" shapes for training and see how it behaves with "morphed" shapes in a GUI*
* Have very few controllable parameters, e.g. gray level (contrast) - fix background, vary object colour, size, location, rotation, &#8592; _Studying the effect of few parameters to the XAI heatmaps_. 
  * Train with shapes fully inside image and test with "occluded", partly out of frame in a GUI*

The Triangles and Squares dataset (see previous comment and links) satisfy some of the above.
*For a GUI concept idea see the figure on our Team Files tab or at the Team's [Sharepoint](https://nlesc.sharepoint.com/sites/DIANNA/Shared%20Documents/General/XAI_GUI.png).

**Comment by elboyran** [comment]
Q for the standup (or earlier if someone self-assignes): 

_Who wants to join me for this issue?_ 

Not sure how much time I will have for actual programming (as much as I would like to) ...

**Comment by cwmeijer** [comment]
For the calculation of the triangle we used this sketch by Leon:
![image](https://user-images.githubusercontent.com/6087314/116364043-1294a880-a804-11eb-95f6-ee3d750918ad.png)

**Comment by elboyran** [comment]
> 
> 
> For the calculation of the triangle we used this sketch by Leon:
> ![image](https://user-images.githubusercontent.com/6087314/116364043-1294a880-a804-11eb-95f6-ee3d750918ad.png)

I thought we were taking of only 2 classes- circle and square?

**Comment by loostrum** [comment]
Initial dataset generation is done: circles with varying size, and triangles with varying size/rotation. All shapes are centred.
ToDo: Add grayscale levels to background / shapes

**Comment by elboyran** [comment]
Should the issue be closed if there is still ToDo?

**Comment by loostrum** [comment]
The grayscale levels were added, but I forgot to mention that here in the issue. Christiaan looked at the PR, so I'll close the issue again and merge.
