### ISSUE TITLE
Find a text dataset suitable for demos

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna-exploration#45]
To illustrate that the XAI methods work on difference data modalities.
An existing available onnx model is a plus.

**Comment by elboyran** [comment]
The [Stanford sentiment treebank dataset](https://nlp.stanford.edu/sentiment/) has been used to demonstrate the methods implemented in [iNNvestigate](https://github.com/albermax/innvestigate), see the [Sentiment analysis](https://github.com/albermax/innvestigate/blob/master/examples/notebooks/sentiment_analysis.ipynb) notebook.

**Comment by elboyran** [comment]
Another starting point could be the [ONNX model zoo](https://github.com/onnx/models) on the section of [Machine comperhension](https://github.com/onnx/models#machine_comprehension)?

**Comment by loostrum** [comment]
A nicely preprocessed version of the Stanford sentiment dataset is available [here](https://gluebenchmark.com/tasks). This version of the dataset has two classes: negative or positive.
NVIDIA NeMo has a [tutorial](https://github.com/NVIDIA/NeMo/blob/main/tutorials/nlp/Text_Classification_Sentiment_Analysis.ipynb) on this dataset, including an export to ONNX, so we have an easy way of generating an ONNX model for it.

I will add the dataset to the surfdrive

**Comment by loostrum** [comment]
Dataset is on Surfdrive, will be synced when Surfdrive issue is solved
