### ISSUE TITLE
Create 2-class MNIST and store in the location

### ISSUE THREAD

**Issue by elboyran** [dianna-ai/dianna-exploration#47]
Options:
1. Very different classes, e.g. "0" and "1"
2. Very similar classes, e.g. "8" and "9" or "5" and ""6 or "1" and "7" or "3" and "8"

Add scripts at [dataset_script folder](https://github.com/dianna-ai/dianna/tree/main/datasets_scripts)

**Comment by elboyran** [comment]
Original dataset: [MNIST dataset](http://yann.lecun.com/exdb/mnist/)
[Tutorial for loading MNIST ] https://www.askpython.com/python/examples/load-and-plot-mnist-dataset-in-python) from [keras datasets](https://keras.io/api/datasets/mnist/)

**Comment by elboyran** [comment]
For motivation of option 2, see for example Figures 15 and 16 on page 30/46 from the [LRP paper](https://storage.googleapis.com/plos-corpus-prod/10.1371/journal.pone.0130140/1/pone.0130140.pdf?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=wombat-sa%40plos-prod.iam.gserviceaccount.com%2F20210421%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20210421T112742Z&X-Goog-Expires=3600&X-Goog-SignedHeaders=host&X-Goog-Signature=0027d6befb073adebe4299f442f1ecd0201251a8729169d262de866163f5590b0bd27f50e61394cd2b28c3f2ee79d834b15b79c2b1c9ed6ac2f245644f376329e22dcbfb87054a11cfda6a9668fef10bcbd6614a070e1490ab95d964b33bbf45b146ddb602d437cb2f4ca629efc09b3a3bcafdd30235dd693d14983e515dd313ce00e6c02d682f24ee8d20cecb975b498de186d9f395eb609f574e8c121964110d81b523e1a01f9e890baf42dfc07e87561a89cddd610fb313a917f007f2ed3a5c5fcd07c3b8114c0cb27d91fb7afadfc71f15cba6a77171445e06d62d02baa4fbac671dbf369975e2369d2e541fdc27b429cfeee33797744e2ef1e0c06db79c)

**Comment by geek-yang** [comment]
As an alternative, the dataset is also available on the website of deepai (click [here](https://deepai.org/dataset/mnist)). About how to load this dataset in python, check this [blog](http://rasbt.github.io/mlxtend/user_guide/data/loadlocal_mnist/).

**Comment by geek-yang** [comment]
The MNIST data is now stored in the surf drive (shared team folder). A notebook to explore and preprocess MNIST data is placed in the repositary.
