### ISSUE TITLE
Investigate convertors for Caffe

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#6]
refs #1 
Do these converters exist? 
- [ ] Caffe2 -> ONNX

Add links to the convertors in the comments below. Also, comment if they were tested and if they work well and such.

**Comment by loostrum** [comment]
caffe2 was merged with pytorch, see [https://caffe2.ai/blog/2018/05/02/Caffe2_PyTorch_1_0.html](https://caffe2.ai/blog/2018/05/02/Caffe2_PyTorch_1_0.html). Should we still test pytorch to ONNX conversion for a specific model using caffe2 functionality?

**Comment by cwmeijer** [comment]
No, this merge has happened in 2018. The stats in #1 mention Caffe2 no longer in 2020. I guess it is really dead enough not to care about anymore. Also, Caffe2's supposed to have ONNX import and export functions builtin according to the same link (and I saw this same information somewhere else, too). So if anyone was still using Caffe2, they won't have a problem to work with ONNX.
I think by knowing this, we can close this issue.
