### ISSUE TITLE
Train model in PyTorch for dataset geometric shapes

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#60]
Script to train the model should be stored in repo
Resulting model (ONNX) saved in the surfdrive

- [x] Make script for preprocessing
- [x] Do hyperparameter search & save model

**Comment by geek-yang** [comment]
Still need to add support for ONNX transformation in this notebook.

**Comment by geek-yang** [comment]
Do we need a separate folder in the repository for the training of models?
