### ISSUE TITLE
Create readmes in the new data file structure

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#69]
For every dataset, create readmes in the new data file structure that introduce each file/script/notebook briefly.

`dataset_preparation` (Not applicable for movie reviews)
- [x] MNIST
- [x] Leaves
- [x] Geometric

`model_generation`
- [x] MNIST
- [x] Leaves
- [x] Geometric
- [x] Movie reviews

**Comment by loostrum** [comment]
I created a branch for this issue (69-readmes) and added readmes for Geometric dataset preparation, and leafs/movie reviews model generation.

**Comment by elboyran** [comment]
Sorry, I forgot what we agreed at the last stand up- adding to the same branch? I guess so.

**Comment by loostrum** [comment]
I think we decided that small PRs are nice, so perhaps a new branch is better. Although I think it doesn't matter too much in this case. I already opened a PR for the changes I made, but you could still add change to that branch, of course.

**Comment by elboyran** [comment]
OK, I'll make a new branch for my small addition.

**Comment by elboyran** [comment]
Maybe we should add the Zenodo DOIs after releasing our datasets there?

**Comment by cwmeijer** [comment]
Readme for geometric model generation in PR #95

**Comment by cwmeijer** [comment]
Readme for mnist model generation in PR #96
