### ISSUE TITLE
Investigate convertors for Darknet

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#7]
refs #1 
Do these converters exist? 
- [ ] Darknet-> ONNX

Add links to the convertors in the comments below. Also, comment if they were tested and if they work well and such.

**Comment by loostrum** [comment]
Darknet does not have a Python interface, although a few 3rd party wrappers mostly for YOLO exist.
Given this, I don't think we have to support it. 
@cwmeijer what do you think?
