### ISSUE TITLE
Check the License of movie reviews

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#70]
Make sure the zip contains some LICENSE file in the end.

**Comment by loostrum** [comment]
The data was downloaded from gluebenchmark.com, who mention "The primary GLUE tasks are built on and derived from existing datasets. We refer users to the original licenses accompanying each dataset."
The original dataset is from https://nlp.stanford.edu/sentiment/index.html. There is a request to cite the paper, but no license. 

Not sure what to do from here - can we add a license to something that's unlicensed?

**Comment by loostrum** [comment]
I've asked the team of the original dataset whether we can use and publish it with a license.

**Comment by cwmeijer** [comment]
Any news already? Did they respond anything to your question?

**Comment by loostrum** [comment]
Nope, no reply yet. I'll send them a reminder

**Comment by elboyran** [comment]
After talking to Lourens and got Rob agreement, there'll be no Zenodo release, so no licensing issue. On the topic of using the data for a (web) demo, we're (probably) good to go. See Louren's email to the DIANNA team on 30 June 2021 and the OK from Rob on 1 July 2021.
