### ISSUE TITLE
Add license to LeafSnap dataset

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#71]
Take into account the original LeafSnap license as our dataset is a derived work. Check on Kaggle.
Add the LICENSE file to the data zip.

**Comment by elboyran** [comment]
Kaggle doesn't say much about the license- only "data files, copyright authors." But the original [site](http://leafsnap.com/dataset/) is live again! No license given there, will contact the authors.

**Comment by elboyran** [comment]
> 
> 
> Kaggle doesn't say much about the license- only "data files, copyright authors." But the original [site](http://leafsnap.com/dataset/) is live again! No license given there, will contact the authors.

Email to the given original email contact bounced back. Will try to contact the [first author](https://neerajkumar.org/projects/leafsnap/) directly.

**Comment by elboyran** [comment]
After talking to Lourens and got Rob agreement, we will release it under CC-By 4.0 for our rights with  a note about the rights of the original authors.
