### ISSUE TITLE
Create zenodo entry for geometric shapes

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#82]

**Comment by cwmeijer** [comment]
Another option for the author order could be to do permute the order so we have several first authors.

**Comment by cwmeijer** [comment]
Blocked by #93.
We are going to present this to the Data SIG before creating a Zenodo entry.

**Comment by elboyran** [comment]
After talking to Lourens and got Rob agreement, CC-By 4.0 should be chosen for the Zenodo release.

**Comment by elboyran** [comment]
### Zenodo entry draft "review":

- Maybe add some possible interested **Communities**, e.g. Computer vision 
- Don't forget to reserve a **DOI**
- Shall we consider a more elaborate **Title**, e.g. _Simple geometric shapes for XAI bench marking ?
- I cannot see all of the **Description**, need to copy & paste somewhere if I'm to comment it fully before meeting. I noticed an English mistake- not single, but plural in the first sentence: geometric shapes. Looks like you are pointing to the DIANNA project- make sure the new name is given int he github link. Maybe be also useful to use the full project name, not only the abbreviation.
- Lets specify English for **Language**
_- We should not forget to eventually update a paper citation whenever we have a paper published about DIANNA._

**Comment by cwmeijer** [comment]
It's published with this doi: https://zenodo.org/record/5012825
