### ISSUE TITLE
Create zenodo entry for leafs

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#84]

**Comment by cwmeijer** [comment]
Blocked by #93.
We are going to present this to the Data SIG before creating a Zenodo entry.

**Comment by elboyran** [comment]
After talking to Lourens and got Rob agreement, there'll be a Zenodo release with CC-By 4.0 license and notes about the original aruthors' rights.

**Comment by elboyran** [comment]
I have created ( saved, but not published yet) a Zenodo entry. Some review of what I have written would be welcome.
I expect logging in is needed to access the [Zenodo link](https://zenodo.org/deposit/5061353).

**Comment by elboyran** [comment]
Screen shots and full text of the **Descriptions** and **Additional Notes** Zenodo fields are now at the _Files_ tab (folder [_Zenodo Screenshots - temp_](https://teams.microsoft.com/_#/files/General?threadId=19%3A1c10950e7e484a80881256db07819b07%40thread.tacv2&ctx=channel&context=Zenodo%2520Screenshots%2520-%2520temp&rootfolder=%252Fsites%252FDIANNA%252FShared%2520Documents%252FGeneral%252FZenodo%2520Screenshots%2520-%2520temp)) and in the _General_ channel [post](https://teams.microsoft.com/l/message/19:1c10950e7e484a80881256db07819b07@thread.tacv2/1625237594795?tenantId=aa3aeacc-6307-42b2-ac05-787dd5c32574&groupId=a78cccb9-a0cc-4394-83b1-c255706f172b&parentMessageId=1625237594795&teamName=DIANNA&channelName=General&createdTime=1625237594795) in _Teams_.

**Comment by elboyran** [comment]
I have fixed Chris's name (sorry ;-) ) and the name of our project (since we have renamed the repo) in the Additional notes. Not visible in he screenshots, but is done ;-).

**Comment by elboyran** [comment]
Done. [Zenodo link](https://zenodo.org/record/5061353).
