### ISSUE TITLE
Ask the Data SIG about our datasets

### ISSUE THREAD

**Issue by cwmeijer** [dianna-ai/dianna-exploration#93]
- Do we release the datasets on Zenodo? Is the work that we did enough to see it as a derived work? This is different of course for each of the datasets.

**Comment by elboyran** [comment]
I am contacting the data SIG on Teams.

**Comment by elboyran** [comment]
[10:07 AM] Elena Ranguelova
    
Dear Data SIG (Data SIG), the DIANNA team has  few questions about the licenses of few datasets we want to release. How can we best approach this- a small improvised meeting of the Data SIG + DIANNA team?

Edited​[11:18 AM] Lourens Veen
    There's this guy at the Center who can advise you on this...he's giving a lunch talk next week.
​[11:19 AM] Elena Ranguelova
    Hi Lourens Veen, sure I know about your knowledge, are you saying that we don't need the whole data SIG?
​[11:23 AM] Lourens Veen
    Well, you're certainly welcome to discuss this in the SIG of course, but it's nice if you involve me so that I can make sure things are synced with Rob as well.
​[11:24 AM] Elena Ranguelova
    With Rob?
​[11:27 AM] Lourens Veen
    Yes, IP issues are done by him at the DT level. Some things are very clear, but sometimes there are licensing situations that are in a gray area or that we don't have policy on, in which case I help people figure out what to do, and then I CC Rob to make sure he knows what's going on.
​[11:28 AM] Lourens Veen
    So if you're just going to put some data online under CC-BY 4.0, then we don't need Rob smile
​[11:28 AM] Elena Ranguelova
    OK, maybe it's easier to talk only to you then?
​[11:29 AM] Lourens Veen
    I think so, if anyone in the SIG wants to join then they're welcome of course
​[11:30 AM] Elena Ranguelova
    OK, I'll try to make a meeting, looking at our agendas.
[11:32 AM] Lourens Veen
    Perfect smile

**Comment by elboyran** [comment]
Meeting with Lourens next Wed, 30 June @ 10:50 a.m.

**Comment by elboyran** [comment]
Summary of the issues is available in this [document](https://nlesc.sharepoint.com/:w:/s/DIANNA/EaAfPyyCx2pJihPqLWu_VHABe5PoxGSAipYINJhdd_UdkQ?e=yH0ckQ) on DIANNA SharePoint. It also has now Lourens' advice during the meeting.

**Comment by elboyran** [comment]
See the email by Lourens to Rob and the team from 30 June 2021.

**Comment by elboyran** [comment]
Rob agrees with Lourens, see email from 1 July 2021.
